trigger:
- master

stages:
- stage: BuildNodes
  jobs:
  - job: Apply
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'CS_Key_Vault'
        KeyVaultName: 'jmtestvault'
        SecretsFilter: '*'
    - script: |
        echo license_accept = \"accept\" >> terraform.tfvars
        echo policy_name = \"$(policy-name)\" >> terraform.tfvars
        echo chef_server_url = \"$(chef-server-url)\" >> terraform.tfvars
        echo chef_user_name = \"admin\" >> terraform.tfvars
        echo chef_user_key = \"admin.pem\" >> terraform.tfvars
        echo chef_client_version = \"$(chef-client-version)\" >> terraform.tfvars
        echo run_list = \"$(run-list)\" >> terraform.tfvars
        echo hab_origin = \"$(hab-origin)\" >> terraform.tfvars
        echo infra_pkg_name = \"$(infra-pkg-name)\" >> terraform.tfvars
        echo audit_pkg_name = \"$(audit-pkg-name)\" >> terraform.tfvars
        echo CLIENT_ID = \"$(azure-client-id)\" >> terraform.tfvars
        echo CLIENT_SECRET = \"$(azure-client-secret)\" >> terraform.tfvars
        echo SUBSCRIPTION_ID = \"$(azure-subscription-id)\" >> terraform.tfvars
        echo TENANT_ID = \"$(azure-tenant-id)\" >> terraform.tfvars
        echo $(admin-pem) | base64 -d > admin.pem
      displayName: 'Build tfvars file'
    - script: |
        echo \[chef_license\] >> ./files/audit_user.toml
        echo acceptance = \"accept-no-persist\" >> ./files/audit_user.toml
        echo "" >> ./files/audit_user.toml
        echo \[automate\] >> ./files/audit_user.toml
        echo enable = true >> ./files/audit_user.toml
        echo server_url = \'$(AUTOMATE-SERVER-NAME)/data-collector/v0/\' >> ./files/audit_user.toml
        echo token = \'$(api-token)\' >> ./files/audit_user.toml
        user = 'admin' >> ./files/audit_user.toml
      displayName: 'Build user.toml for effortless audit'
    - script: |
        echo \[chef_license\] >> ./files/infra_user.toml
        echo acceptance = \"accept-no-persist\" >> ./files/infra_user.toml
        echo "" >> ./files/infra_user.toml
        echo \[automate\] >> ./files/infra_user.toml
        echo enable = true >> ./files/infra_user.toml
        echo server_url = \'$(AUTOMATE-SERVER-NAME)/data-collector/v0/\' >> ./files/infra_user.toml
        echo token = \'$(api-token)\' >> ./files/infra_user.toml
      displayName: 'Build user.toml for effortless infra'
    - script: 'terraform init'
      displayName: 'Initialize Terraform modules'
    - script: 'terraform validate'
      displayName: 'Validate Terraform modules'
    - script: 'terraform apply --auto-approve'
      displayName: 'Build infrastructure'